language: python
python:
- '3.6'
script:
- true
deploy:
  provider: pypi
  user: congzhang
  password:
    secure: hDEwgsMBihCVwq7stSKLRw/ht4faeTRAN2QmgzTLz5xGWz33RLhoL2fq8JwukGvQvugqqHzp3LjDNqd2remI+s2tNMsDD3EKdlx4738iefbDd2zbow/2P8z4BQnUsWcdqpBMyPutQIMWIDPLJYnf2DDwz68oNDcAwxToZyQkE67q9kBW477UBmfB0s5jVWCuT+tqEmlpq0asbBxNMKKoFGFcfGXHgXptVQ8G+8THDxJpEKIbiO3LN3vqUznIPD9mfGKV5GOsjJgsIUicPKuLBnOpZ52pXIkdKUUD31Tl0XtIZmYKIeLXKn3yYfT3angpb/UVx+eeUAnXT36Hi5pLDHoqYkibKeIPeGXd07SmC4ZFbi25mlYkIJVXmVoEJqsV++sHFAJTnHXozTeCHbWTcVeZURuvySFF6SI1PbBNeXk9DL6vnRmrbWf93G9gu7IRma2FZIrlP4kLB4nxPO1GPFz5Bf//fHO8lFcokcn3zt8DvHeZLbVbtC/UMmTSvgPez2SiSqHFDFxCFom5yDsGkGMGBhspp21VLKkAqnOh6aZ9pnWF70/FYCcLCDtUU1KiDDuJQhXgmN6D3zIVokgHEsOdRLv3QSMwYNf81OdGQj4EGAJtiJ4PcKjgJelAWT8DC8gGJ95/cLNrugYWxePv5GbsnrHrJ/u9A+1RI1XXPlU=
  on:
    distributions: sdist bdist_wheel
    repo: congzhangzh/uproxy
